#!/bin/bash

# SLURM does not support using variables in the #SBATCH lines within a job script.
# We use them here as guidelines, and they should be replaced by constant values.
NTASKS=#2,4,8,16,32,64

#SBATCH --job-name="likwid_${NTASKS}"

#SBATCH --nodes=1
#SBATCH --account=proj16
#SBATCH --partition=prod
#SBATCH --constraint=clx
#SBATCH --time=1-00:00:00
#SBATCH --exclusive
#SBATCH --mem=0
#SBATCH --output="%x.out"

# STEPS must be compiled (manually with CMake and not with spack) with the same environment as in this batch script
export PYTHONPATH=Path/To/STEPS:$PYTHONPATH

module purge
module load archive/2021-12 git cmake python/3.8.3 gcc boost
module unload hpe-mpi

spack load mpich@3.3.2
spack load petsc@3.14.1
spack load gmsh@4.4.1
spack load caliper@2.6.0

module load likwid/5.2.0

echo "*****"
echo ${NTASKS}
echo $((NTASKS / 2))
echo "*****"

export STEPS_INSTRUMENTOR_MPI_BARRIER="before;after"

#time likwid-mpirun -d -np ${NTASKS} -m -g MEM_DP \
time likwid-mpirun -d -np ${NTASKS} -nperdomain S:$((NTASKS / 2)) -m -g MEM_DP \
python3 caburstfull_single_script.py 1 ../CaBurstUnifiedMesh/split_${NTASKS}/steps4/CNG_segmented_2_split_${NTASKS} 1
